name: census
channels:
  - defaults
  - conda-forge
dependencies:
- python=3.11
- pip
- pip:
      - anndata==0.12.4
      - cellxgene-census==1.17.0
      - matplotlib==3.10.7
      - numpy==2.3.4
      - pandas==2.3.3
      - scanpy==1.11.5
      - pytorch==2.9.1
      - tiledbsoma==2.1.0
      - torchdr ==0.3
